### ISSUE TITLE
Spinner animations are inconsistent

### ISSUE THREAD

**Issue by mmellado** [airtame/airtame-gooey#19]
- Fix the timing for the spinner animation
- Add inverse spinner animation

**Comment by mmellado** [comment]
Will break spinner into 3 different spinner options:
- spinner
- inverted
- steped (which stops before restarting)

**Comment by elvisvoer** [comment]
For the stepped here should be the steps:

```scss
@keyframes spin {
    0% {
      transform: rotate(0deg);
    }

    50% {
      transform: rotate(180deg);
    }

    100% {
      transform: rotate(359deg);
    }
  }

  @keyframes spin-reverse {
    0% {
      transform: rotate(0deg);
    }

    50% {
      transform: rotate(-180deg);
    }

    100% {
      transform: rotate(-359deg);
    }
  }
```
