### ISSUE TITLE
Mixing param for tooltip bubble :before and :after

### ISSUE THREAD

**Issue by elvisvoer** [airtame/airtame-gooey#24]
I find myself in the position of writing this scss to position the bubble triangle in the tooltip:
```scss
.gooey-tooltip__bubble {
  &:before {
    left: 31px;
  }

  &:after {
    left: 32px;
  }
}
```
Maybe we can have a mixin param that computes those values.
